# AWS Athena Configuration Properties
aws.region=us-east-2
athena.output.s3.bucket=s3://home-dongyang/athena-results/
athena.dollars.per.tb=5.0

# Workload Configuration Properties
query.file.path=/home/gengdy/athena-experiment/workload/queries-mini.txt
results.file.path=/home/gengdy/athena-experiment/workload/result.txt